name: Monthly Full Backup

on:
  schedule:
    # 毎月1日の午前3時に実行
    - cron: '0 3 1 * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  monthly-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create backup directory
        run: mkdir -p backups/monthly
        
      - name: Create backup timestamp
        run: echo "BACKUP_DATE=$(date +%Y%m)" >> $GITHUB_ENV
        
      - name: Create monthly backup file
        run: |
          echo "# Monthly Full Backup - ${{ env.BACKUP_DATE }}" > backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "## システム情報" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- 日付: $(date)" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- システム: 職場管理システム" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- データベース: Supabase PostgreSQL" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- バックアップ種別: 月次完全バックアップ" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- ステータス: ⚠️ 手動実行が必要" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "## 月次完全バックアップ手順" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "このリマインダーが作成されたので、以下の手順で完全バックアップを実行してください：" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "### 1. Supabase SQL Editor でbackup-script.sqlを実行" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "\`\`\`sql" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "-- 全テーブルのデータ件数確認" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "SELECT 'departments' as table_name, COUNT(*) as record_count FROM departments" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "UNION ALL SELECT 'priorities', COUNT(*) FROM priorities" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "UNION ALL SELECT 'statuses', COUNT(*) FROM statuses" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "UNION ALL SELECT 'schedules', COUNT(*) FROM schedules" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "UNION ALL SELECT 'handovers', COUNT(*) FROM handovers" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "UNION ALL SELECT 'tasks', COUNT(*) FROM tasks;" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "-- 重要テーブルの完全バックアップ" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "SELECT * FROM tasks ORDER BY created_at DESC;" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "SELECT * FROM handovers ORDER BY created_at DESC;" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "SELECT * FROM schedules ORDER BY date DESC;" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "\`\`\`" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "### 2. 結果をCSVでダウンロード" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- 各クエリの結果をCSV形式でダウンロード" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- ファイル名: \`tasks_${{ env.BACKUP_DATE }}.csv\`, \`handovers_${{ env.BACKUP_DATE }}.csv\`, \`schedules_${{ env.BACKUP_DATE }}.csv\`" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "### 3. ローカル保存" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- 専用フォルダに保存: \`backups/monthly/${{ env.BACKUP_DATE }}/\`" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- 重要なファイルは複数の場所にバックアップを推奨" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "### 4. 完了確認" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- [ ] データ件数の確認完了" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- [ ] CSVファイルのダウンロード完了" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- [ ] ローカル保存完了" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "- [ ] バックアップの動作確認完了" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "## 次回バックアップ予定" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          echo "次回の月次バックアップは $(date -d '+1 month' '+%Y年%m月1日') に実行予定です。" >> backups/monthly/backup-${{ env.BACKUP_DATE }}.md
          
      - name: Clean old monthly backups (keep last 12 months)
        run: |
          find backups/monthly -name "backup-*.md" -mtime +365 -delete || true
          
      - name: Commit monthly backup
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backups/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Monthly backup reminder: ${{ env.BACKUP_DATE }}"
            git push
          fi